// File generated by FlutterFire CLI.
// Project: laxshot-app-d44c9
// See: https://firebase.flutter.dev/docs/cli

// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) return web;
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  // Web config — same project, web API key from Firebase console
  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCFzxUGqmuzrDZmDZfvgqCtcBLDJIqG47s',
    appId: '1:138884416580:web:laxshot_web',
    messagingSenderId: '138884416580',
    projectId: 'laxshot-app-d44c9',
    storageBucket: 'laxshot-app-d44c9.firebasestorage.app',
    authDomain: 'laxshot-app-d44c9.firebaseapp.com',
  );

  // ⚠️  Android: google-services.json currently registers com.laxshot.app
  // but the app's applicationId is com.laxshot.laxshot.
  // ACTION REQUIRED: In Firebase console → Project Settings → Add Android app
  //   Package name: com.laxshot.laxshot
  //   Download the new google-services.json → android/app/google-services.json
  //   Then update appId below with the new GOOGLE_APP_ID value.
  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCFzxUGqmuzrDZmDZfvgqCtcBLDJIqG47s',
    appId: '1:138884416580:android:015ab78ff4425532142811', // TODO: update after re-registering
    messagingSenderId: '138884416580',
    projectId: 'laxshot-app-d44c9',
    storageBucket: 'laxshot-app-d44c9.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCgr_oOBZkT4tkfmxv3dAkloXvAXFyhD1g',
    appId: '1:138884416580:ios:7d6a97822df61ba7142811',
    messagingSenderId: '138884416580',
    projectId: 'laxshot-app-d44c9',
    storageBucket: 'laxshot-app-d44c9.firebasestorage.app',
    iosBundleId: 'com.laxshot.laxshot',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCgr_oOBZkT4tkfmxv3dAkloXvAXFyhD1g',
    appId: '1:138884416580:ios:7d6a97822df61ba7142811',
    messagingSenderId: '138884416580',
    projectId: 'laxshot-app-d44c9',
    storageBucket: 'laxshot-app-d44c9.firebasestorage.app',
    iosBundleId: 'com.laxshot.laxshot',
  );
}
