// File generated by FlutterFire CLI.
// Project: laxshot-app-d44c9
// See: https://firebase.flutter.dev/docs/cli

// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) return web;
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  // Web config — same project, web API key from Firebase console
  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCFzxUGqmuzrDZmDZfvgqCtcBLDJIqG47s',
    appId: '1:138884416580:web:laxshot_web',
    messagingSenderId: '138884416580',
    projectId: 'laxshot-app-d44c9',
    storageBucket: 'laxshot-app-d44c9.firebasestorage.app',
    authDomain: 'laxshot-app-d44c9.firebaseapp.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCFzxUGqmuzrDZmDZfvgqCtcBLDJIqG47s',
    appId: '1:138884416580:android:015ab78ff4425532142811',
    messagingSenderId: '138884416580',
    projectId: 'laxshot-app-d44c9',
    storageBucket: 'laxshot-app-d44c9.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCgr_oOBZkT4tkfmxv3dAkloXvAXFyhD1g',
    appId: '1:138884416580:ios:eb1f3eb2a97ccfa0142811',
    messagingSenderId: '138884416580',
    projectId: 'laxshot-app-d44c9',
    storageBucket: 'laxshot-app-d44c9.firebasestorage.app',
    iosBundleId: 'com.laxshot.app',
  );
}
